@startuml Основной процесс взаимодействия

start 
:Пользователь зашел на сайт;

if (Есть ли у пользователя аккаунт?) then (да)
else (нет)  
    :Регистрация;
endif
:Авторизация;
repeat :Отображение страницы управления курсами;

    switch ()
    case (Удалить курс) 
        :Удалить курс;
        stop
    case (Создать курс)
        :Создать новый курс;
        :Отобразить страницу создания курса;
        :Создать шаблон курса;
    case (Редактировать курс)
        :Отобразить созданный курс;
        switch ()
        case (Экспортировать) 
            :Экспортировать курс;
            stop
        case (Редактировать)
        endswitch
    endswitch

    :Редактировать название курса;
    :Редактировать тему курса;
    :Редактировать описание курса;

    repeat :Редактировать структуру курса;
        switch ()
        case ()
            :Задать структуру курса вручную;
        case ()
            :Сгенерировать структуру курса;
        endswitch
    repeat while (Изменить структуру курса) is (да) not (нет)

    repeat :Редактировать контент топика;
        switch ()
        case ()
            :Задать контент топика вручную;
        case ()
            :Сгенерировать контент топика;
        endswitch
    repeat while (Изменить контент топика (есть еще топики у которых надо изменить контент?)) is (да) not (нет)

    repeat :Редактировать тест;
        switch ()
        case ()
            :Задать тест вручную;
        case ()
            :Сгенерировать тест;
        endswitch
    repeat while (Изменить тест (есть еще тесты которые надо изменить?)) is (да) not (нет)

    :Завершить редактирование курса;

repeat while (Экспортировать курс?) is (нет) not (да)

:Экспортировать курс;
stop

@enduml