@startuml Recipe Service. Диаграмма компонентов

' Скины и стили
skinparam componentStyle rectangle
skinparam wrapWidth 250
skinparam packageStyle rectangle 
skinparam monochrome true
skinparam defaultFontName Arial

left to right direction

actor Модератор as m

rectangle "Общий фукнционал модератора" {
  usecase "Управление пользовательским контентом" as MF1
  usecase "Удаление курса" as MF1.1

  usecase "Управление пользователями" as MF2
  usecase "Управление информацией" as MF2.1
  usecase "Изменение пользовательской информации (открытой)" as MF2.1.1
  usecase "Удаление пользователя" as MF2.2
  usecase "Удаление информации связанной с пользователем" as MF2.2.1

}

m --> MF1
MF1 <.. MF1.1 : extend
m --> MF2
MF2 <.. MF2.1 : extend
MF2.1 ..> MF2.1.1 : include
MF2 <.. MF2.2 : extend
MF2.2 ..> MF2.2.1 : include

@enduml